# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
