# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 14:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0003_auto_20170524_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
