# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0006_document_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldocument',
            name='comment',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
