# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0007_historicaldocument_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
