# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapi', '0008_auto_20170529_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='metadata',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='historicaldocument',
            old_name='metadata',
            new_name='data',
        ),
    ]
