# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='analytic',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Domain'),
        ),
        migrations.AddField(
            model_name='analytic',
            name='page_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.PageState'),
        ),
    ]
