# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Domain')),
                ('page_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.PageState')),
            ],
        ),
    ]
