# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c2c_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parameters',
            field=models.TextField(blank=True, validators=[www.models._is_json]),
        ),
    ]
