# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20170312_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='outing_queries',
            field=models.TextField(default="{'français':{l:'fr'}}", validators=[www.models._is_json]),
        ),
    ]
