# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_profile_outing_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images_queries',
            field=models.TextField(default='{"français":{"l":"fr"}}', validators=[www.models._is_json]),
        ),
        migrations.AddField(
            model_name='profile',
            name='routes_queries',
            field=models.TextField(default='{"français":{"l":"fr"}}', validators=[www.models._is_json]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='outing_queries',
            field=models.TextField(default='{"français":{"l":"fr"}}', validators=[www.models._is_json]),
        ),
    ]
