# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170312_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='images_queries',
            new_name='image_queries',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='routes_queries',
            new_name='route_queries',
        ),
    ]
