# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20170312_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xreport_queries',
            field=models.TextField(default='{}', validators=[www.models._is_json]),
        ),
    ]
