# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 22:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_profile_xreport_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parameters',
            field=models.TextField(blank=True, default='{}', validators=[www.models._is_json]),
        ),
    ]
